name: build_windows

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: windows-latest
    steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python -v

    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        path: 'scripts'


    - run: dir $GITHUB_WORKSPACE
    - name: pre-build
      run: |
        $fileExists = Test-Path -Path C:\Users\runneradmin\AppData\Local\Arduino15
        if ($fileExists) {
            Remove-Item -Recurse -Force -Path C:\Users\runneradmin\AppData\Local\Arduino15
            mkdir C:\Users\runneradmin\AppData\Local\Arduino15
        }

    - name: Donwload .zip core
      run: |
        curl -L -o arduino.zip https://github.com/SiliconLabs/arduino/releases/download/1.0.0/silabs_arduino_core-1.0.0.zip
        7z x -y arduino.zip -o"C:\Users\runneradmin\AppData\Local\Arduino15\packages\SiliconLabs\hardware\silabs"
        ren C:\Users\runneradmin\AppData\Local\Arduino15\packages\SiliconLabs\hardware\silabs\silabs-arduino 1.0.0
        echo "================="
        dir C:\Users\runneradmin\AppData\Local\Arduino15\packages\SiliconLabs\hardware\silabs\1.0.0

    - name: Install arduino-cli
      run: |
        mkdir tools
        curl -L -o arduino_cli.zip https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Windows_64bit.zip
        7z x -y arduino_cli.zip -o"tools"

        dir tools
        echo "================="
        tools\arduino-cli.exe board listall bgm220
        tools\arduino-cli.exe config dump

    - name: Install gcc_12
      run: |
        mkdir C:\Users\runneradmin\AppData\Local\Arduino15\packages\SiliconLabs\tools\gcc-arm-none-eabi
        curl -L -o gcc.zip https://github.com/SiliconLabs/arduino/releases/download/1.0.0/arm-gnu-toolchain-12.2.rel1-mingw-w64-i686-arm-none-eabi.zip
        7z x -y gcc.zip -o"C:\Users\runneradmin\AppData\Local\Arduino15\packages\SiliconLabs\tools\gcc-arm-none-eabi"
        echo "================="
        dir C:\Users\runneradmin\AppData\Local\Arduino15\packages\SiliconLabs\tools\gcc-arm-none-eabi
        ren C:\Users\runneradmin\AppData\Local\Arduino15\packages\SiliconLabs\tools\gcc-arm-none-eabi\arm-gnu-toolchain-12.2.rel1-mingw-w64-i686-arm-none-eabi 12.2.rel1

    - name: Compile example
      run: |
        mkdir output
        tools\arduino-cli.exe compile -b $variant $arduino_lib_dir\$project_path --libraries $arduino_lib_dir --output-dir output
        echo "================="
        dir output
      env:
        variant: SiliconLabs:silabs:bgm220explorerkit_precomp
        arduino_lib_dir: C:\Users\runneradmin\AppData\Local\Arduino15\packages\SiliconLabs\hardware\silabs\1.0.0 
        project_path: libraries\ezBLE\examples\ezBLE_callbacks\ezBLE_callbacks.ino

    #- run: mkdir arduino/temp
    - name: Checkout another repo
      uses: actions/checkout@v4
      with:
        repository: 'SiliconLabs/arduino'
        ref: 'main'
        path: 'arduino\temp'

    - name: Run script test
      run: |
        echo $GITHUB_WORKSPACE
        dir arduino\temp
        echo "======== 000 ========="
        xcopy arduino\temp\test\test_sketch $GITHUB_WORKSPACE
        dir $GITHUB_WORKSPACE
        
        python scripts\tool_modify.py arduino\temp\test tools\arduino-cli.exe
        echo "========111 ========="
        dir arduino\temp\test
        python arduino\temp\test\test_build_modified.py "quick"
