name: CI

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python -v

    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        path: 'scripts'

    - run: mkdir -p arduino/.arduino15/packages/SiliconLabs/hardware/siliconlabs/1.0.0
    - name: Checkout another repo
      uses: actions/checkout@v4
      with:
        repository: 'SiliconLabs/arduino'
        ref: 'main'
        # lfs: 'true'
        path: 'arduino/.arduino15/packages/SiliconLabs/hardware/siliconlabs/1.0.0'
        # path: 'arduino'

    - name: Install arduino-cli
      run: |
        ls scripts
        echo "================="
        ls 
        arduino/.arduino15/packages/SiliconLabs/hardware/siliconlabs/1.0.0
        echo "================="
        mkdir -p tools
        curl -L -o arduino_cli.tgz https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
        tar -xvf arduino_cli.tgz -C tools
        ls tools
        ./tools/arduino-cli core list
        echo "================="
        ./tools/arduino-cli board listall bgm220 --config-file scripts/arduino-cli.yaml

    - name: Install gcc_12
      run: |
        mkdir -p arduino/.arduino15/packages/SiliconLabs/tools/gcc-arm-none-eabi
        curl -L -o gcc.tgz https://github.com/SiliconLabs/arduino/releases/download/1.0.0/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
        tar -xvf gcc.tgz -C arduino/.arduino15/packages/SiliconLabs/tools/gcc-arm-none-eabi > /dev/null
        mv arduino/.arduino15/packages/SiliconLabs/tools/gcc-arm-none-eabi/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi arduino/.arduino15/packages/SiliconLabs/tools/gcc-arm-none-eabi/12.2.rel1

    - name: Compile example
      run: |
        ./tools/arduino-cli core list --libraries arduino
        ./tools/arduino-cli compile -b siliconlabs:bgm220 libraries/ezBLE/examples/ezBLE_callbacks/ezBLE_callbacks.ino --libraries arduino
    - run: python arduino/test/test_build.py "quick"

# jobs:
#   linux:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout another repo
#         uses: actions/checkout@v4
#         with:
#           repository: 'SiliconLabs/arduino'
#           ref: 'main'
#         - run: ls .

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - run: choco install ninja
  #     - run: ninja --version

  # mac:
  #   runs-on: macos-latest
  #   steps:
  #     - run: brew install ninja 
  #     - run: ninja --version

      # - name: Download articats
      #   uses: actions/download-artifact@v2
      # - name: Place artifacts
      #   shell: bash
      #   run: |
      #     rm -rf dist
      #     mv artifact/* ./