name: CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout another repo
        uses: actions/checkout@v4
        with:
          repository: 'SiliconLabs/arduino'
          ref: 'main'
        - run: ls .

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - run: choco install ninja
  #     - run: ninja --version

  # mac:
  #   runs-on: macos-latest
  #   steps:
  #     - run: brew install ninja 
  #     - run: ninja --version
