name: CI

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python -v
    - run: mkdir -p /root/.arduino15/package/SiliconLabs/1.1.0

    - name: Checkout another repo
      uses: actions/checkout@v4
      with:
        repository: 'SiliconLabs/arduino'
        ref: 'main'
        # lfs: 'true'
        path: '/root/.arduino15/package/SiliconLabs/1.1.0'

    - name: Install arduino-cli
      run: |
        mkdir -p tools
        curl -L -o arduino_cli.tgz https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
        tar -xvf arduino_cli.tgz -C tools
        ls tools
        ./tools/arduino-cli core list
        ./tools/arduino-cli config dump
      
    - run: ls /root/.arduino15
    - run: python arduino/test/test_build.py "quick"

# jobs:
#   linux:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout another repo
#         uses: actions/checkout@v4
#         with:
#           repository: 'SiliconLabs/arduino'
#           ref: 'main'
#         - run: ls .

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - run: choco install ninja
  #     - run: ninja --version

  # mac:
  #   runs-on: macos-latest
  #   steps:
  #     - run: brew install ninja 
  #     - run: ninja --version
