name: test

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: windows-latest
    steps:
    - name: Run script test
      run: |
        echo "my_tool=$env:GITHUB_WORKSPACE/tools/arduino-cli.exe" >> $env:GITHUB_ENV

        ECHO $env:my_tool
        
        ECHO $env:my_tool > var.txt
        dir .
        powershell -command "(get-content var.txt) -replace '[\x5C]+', '/' | set-content var.txt"
        set /p my_tool =< var.txt
        echo "::set-output name=version::$(Get-Content var.txt)"
        echo "====================="
        ECHO ${{ steps.read_version.outputs.version }}
