name: test

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: windows-latest
    steps:
    - name: Run script test
      run: |
        echo "my_tool=$env:GITHUB_WORKSPACE/tools/arduino-cli.exe" >> $env:GITHUB_ENV
        echo $env:my_tool>var.txt
        powershell -command "(get-content var.txt) -replace '[\x5C]+', '/' | set-content var.txt"
        set /p my_tool=<var.txt
        echo $env:my_tool
