name: build_windows

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: windows-latest
    steps:
    - name: Run script test
      run: |
        echo $GITHUB_WORKSPACE
        echo $GITHUB_WORKSPACE\tools\arduino-cli.exe

        echo $env:GITHUB_WORKSPACE
