name: test

on:
  push:
    paths:
     - .github/workflows/test.yml

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run script test
      run: |
          sudo apt-get install git-lfs -y
          git lfs install --skip-repo
